# Site settings
title: "Barry Threw | art technology"
email: me@barrythrew.com
description: > # this means to ignore newlines until "baseurl:"
    Barry Threw is a curator, technologist, designer, cultural producer & strategist 
    working across digital art, built environments, experiential & immersive media, 
    architectural projection mapping, and technology platforms.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://barrythrew.com" # the base hostname & protocol for your site

instagram_username: barrythrew
facebook_username: barrythrew
twitter_username: barrythrew
github_username:  barrythrew
linkedin_username: barrythrew

permalink: pretty

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

collections:
  projects:
    output: true