# Site settings
title: "Barry Threw"
email: me@barrythrew.com
description: > # this means to ignore newlines until "baseurl:"
    Barry Threw is sometimes a curator, technologist, designer, cultural producer & strategist. 
    He works across digital art, built environments, experiential & immersive media, 
    architectural projection mapping, and technology platforms.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://barrythrew.com" # the base hostname & protocol for your site

instagram_username: barrythrew
facebook_username: barrythrew
twitter_username: barrythrew
github_username:  barrythrew
linkedin_username: barrythrew

permalink: pretty

exclude: 
  - docker
  - docker-compose.yml
  - nginx.conf

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

collections:
  projects:
    output: true